sudo: required

services:
  - docker                  

before_install:            
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

script:
  - ./check_uniqueness_of_rule_ids.sh
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -D /documents/output index.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf asciidoctor/docker-asciidoctor asciidoctor-pdf -D /documents/output index.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoctor-epub3 asciidoctor/docker-asciidoctor asciidoctor-epub3 -D /documents/output index.adoc

after_error: 
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf
  - docker logs asciidoc-to-epub3

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf
  - docker logs asciidoc-to-epub3

after_success: ./travis_deploy.sh