sudo: required

services:
  - docker                  

before_install:            
  - make pull

script:
  - make check-rules > check-rule-ids.log
  - make all

after_error:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf
  - docker logs asciidoc-to-epub3
  - cat check-rule-ids.log

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf
  - docker logs asciidoc-to-epub3
  - cat check-rule-ids.log

after_success: scripts/deploy-travis.sh
